#!/bin/bash
#SBATCH --job-name=project_mesure
#SBATCH -n 1
#SBATCH -c 32
#SBATCH -o %x_%j.out
#SBATCH -e %x_%j.err



#serial mesure
echo -n "" > 04_result_soft.txt

#OMP mesure
for((N=10;N<=1000000;N*=10))
do
    for((i=1;i<=16;i+=1))
    do
        echo -en $N "\n" >> 04_result_soft.txt
        srun -c 12 ./pi_s $N $i >> 04_result_soft.txt
        OMP_NUM_THREADS=12 srun -c 12 ./pi_p $N $i >> 04_result_soft.txt
    done
done