INSERT INTO templates_table (name, question_count, time_limit) VALUES ('Node.js Test', 20, 60);

INSERT INTO questions_table (template_ID, question_text, options, answer) VALUES
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'Which of the following best describes Node.js?', 'A) A programming language\nB) A framework\nC) A runtime environment for JavaScript\nD) An operating system', 'C) A runtime environment for JavaScript'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What type of programming language is JavaScript, which Node.js is based on?', 'A) Functional programming language\nB) Object-oriented programming language\nC) Scripting language\nD) Compiled language', 'C) Scripting language'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is the main benefit of asynchronous programming in Node.js?', 'A) It allows for parallel execution of tasks\nB) It simplifies the code structure\nC) It ensures deterministic execution order\nD) It eliminates the need for callbacks', 'A) It allows for parallel execution of tasks'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'Which keyword is commonly used in JavaScript for handling asynchronous operations?', 'A) async\nB) await\nC) sync\nD) done', 'B) await'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'Which keyword is used to import modules in Node.js?', 'A) import\nB) require\nC) include\nD) module', 'B) require'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is the purpose of the "npm init" command?', 'A) To install Node.js on your system\nB) To initialize a new Node.js project and create a package.json file\nC) To update all installed packages to their latest versions\nD) To start a new Node.js server', 'B) To initialize a new Node.js project and create a package.json file'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How do you specify the port number for an HTTP server in Node.js?', 'A) By passing it as an argument to the createServer method\nB) By setting the PORT environment variable\nC) By configuring it in the package.json file\nD) By passing it as an argument to the listen method', 'D) By passing it as an argument to the listen method'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'Which method is used to handle incoming HTTP requests in an HTTP server?', 'A) request\nB) handleRequest\nC) on\nD) handle', 'C) on'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How does an HTTP server identify the type of request being made by a client?', 'A) By inspecting the request body\nB) By analyzing the request URL\nC) By examining the request headers\nD) By checking the request method', 'D) By checking the request method'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is the purpose of the "req" and "res" objects in Node.js HTTP servers?', 'A) "req" represents the response sent by the server, while "res" represents the request received from the client\nB) "req" represents the request received from the client, while "res" represents the response sent by the server\nC) Both "req" and "res" represent the same object, which contains information about the HTTP request\nD) Neither "req" nor "res" are valid objects in Node.js HTTP servers', 'B) "req" represents the request received from the client, while "res" represents the response sent by the server'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How do you define a route in an Express.js application?', 'A) By specifying the route path and a callback function to handle the request\nB) By creating a separate JavaScript file for each route\nC) By configuring routing rules in the package.json file\nD) By using the "route" method provided by the Express.js framework', 'A) By specifying the route path and a callback function to handle the request'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is middleware chaining in Express.js?', 'A) A mechanism for passing control from one middleware function to the next in the chain\nB) A technique for combining multiple middleware functions into a single function\nC) A method for handling errors in the middleware stack\nD) A process for routing requests to the appropriate route handler', 'A) A mechanism for passing control from one middleware function to the next in the chain'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is the primary purpose of Express.js in web development?', 'A) To handle front-end logic\nB) To manage databases\nC) To create server-side applications and APIs\nD) To design user interfaces', 'C) To create server-side applications and APIs'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How do you create a new route in an Express.js application?', 'A) By defining a new function with the desired route logic and using app.route() to mount it\nB) By using the "route" method provided by Express.js\nC) By using app.get(), app.post(), app.put(), or app.delete() methods with the desired route path and handler function\nD) By configuring routing rules in the package.json file', 'C) By using app.get(), app.post(), app.put(), or app.delete() methods with the desired route path and handler function'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is MongoDB?', 'A) A relational database management system\nB) A NoSQL database management system\nC) A front-end JavaScript framework\nD) A back-end JavaScript framework', 'B) A NoSQL database management system'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How do you connect to a MongoDB database in a Node.js application?', 'A) By creating a connection string and passing it to the mongoose.connect() method\nB) By using the require() function to import the MongoDB package and calling connect() method\nC) By configuring the database connection settings in the package.json file\nD) By including the database connection settings as part of the route paths', 'A) By creating a connection string and passing it to the mongoose.connect() method (for MongoDB with Mongoose)'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is Mongoose?', 'A) A front-end JavaScript framework\nB) A back-end JavaScript framework\nC) An Object Data Modeling (ODM) library for MongoDB and Node.js\nD) A NoSQL database management system', 'C) An Object Data Modeling (ODM) library for MongoDB and Node.js'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is authentication?', 'A) The process of granting access to users based on their identity\nB) The process of encrypting data for secure transmission\nC) The process of managing database connections\nD) The process of designing user interfaces', 'A) The process of granting access to users based on their identity'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is authorization?', 'A) The process of verifying the integrity of data\nB) The process of managing user identities\nC) The process of granting permissions to authenticated users\nD) The process of handling errors in a web application', 'C) The process of granting permissions to authenticated users'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'How do you handle query parameters in RESTful API endpoints?', 'A) By passing them as part of the route path\nB) By using the req.query object in Express.js\nC) By encrypting them for secure transmission\nD) By including them as part of the request body', 'B) By using the req.query object in Express.js'),
((SELECT template_ID FROM templates_table WHERE name='Node.js Test'), 'What is end-to-end testing?', 'A) Testing individual units or components of a software application in isolation\nB) Testing the entire application as a whole, including its external dependencies\nC) Testing user interfaces\nD) Testing database connections', 'B) Testing the entire application as a whole, including its external dependencies');
